### ISSUE TITLE
Unable to choose kernel

### ISSUE THREAD

**Issue by Brainor** [microsoft/vscode-jupyter#12160]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Everything works fine on `2022.11.1003281132` but not on `2022.11.1003291043` and `2022.11.1003301027`.
2. When I open a `*.ipynb` file, the bottom left corner shows error message: `Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.`
![image](https://user-images.githubusercontent.com/5477995/203783966-ded8c31f-7cf1-487b-9d56-9985561ba378.png)
and the Developer Tools show this error message
![image](https://user-images.githubusercontent.com/5477995/203784351-79cee9a9-a401-4fe3-b03c-5959851db951.png)
Just like the Jupyter logs, it says that `TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function`, which frankly doesn't come up in github search engine.
3. the ipynb file opens fine, but the `Select Kernel` button is malfunctioning.
![image](https://user-images.githubusercontent.com/5477995/203784602-f92ab82f-51ca-472d-ad03-30fed9641356.png)
The button in Jupyter version `2022.11.1003281132` works fine as below.
![image](https://user-images.githubusercontent.com/5477995/203784973-12ca94c6-6d30-4212-a63d-1de25ac752bf.png)
4. The `Jupyter Show Output` command shows an error message: Command 'Jupyter: Show Output' resulted in an error (command 'jupyter.viewOutput' not found). So I paste the OUTPUT panel > Jupyter output in the issue's `Jupyter logs` section.
5. I found an [issue](https://github.com/microsoft/vscode/issues/165959) in vscode that talks about `createNotebookControllerDetectionTask` but can't quite understand it; so maybe it's a vscode problem?

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Jupyter Extension Version

v2022.11.1003301027

### Jupyter logs
<details>
    <summary>logs</summary>

```shell
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.11.1003301027.
Python Extension Version: 2022.18.2.
Workspace folder d:\ouweike\code\EmbyDownloader
info 20:18:06.320: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
error 20:18:06.681: Failure during activation. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2070921)
	at h.activate (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2069968)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163973)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
error 20:18:06.682: sendStartupTelemetry() failed. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2070921)
	at h.activate (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2069968)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163973)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
error 20:18:06.683: extension activation failed [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2070921)
	at h.activate (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2069968)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163973)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
error 20:18:06.692: Failed to active the Jupyter Extension [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2070921)
	at h.activate (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2069968)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163973)
	at c:\Users\brain\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

</details>

### Coding Language and Runtime Version

Python v3.11.0

### Language Extension Version (if applicable)

v2022.18.2

### Anaconda Version (if applicable)

22.9.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
thanks for filling this issue.
when using the new insider version, please update to the latest insider version of vscode.

**Comment by Brainor** [comment]
> update to the latest insider version of vscode.

Oh I think you are right.
The stable version of Jupyter (v2022.9.1303220346) has this #10846 issue, so I switched to the pre-release version according to the [comment](https://github.com/microsoft/vscode-jupyter/issues/10846#issuecomment-1303689876), which is preferably run with vscode-insider that I didn't know about.
I guess I'll have to wait for the update of the stable Jupyter then.
Thank you for your help.

**Comment by alanyoungCN** [comment]
@DonJayamanne  But the stable version has a bug reported in https://github.com/microsoft/vscode-jupyter/issues/11938. To prevent the duplicated intellisence I HAVE TO use the insider version according to https://github.com/microsoft/vscode-jupyter/issues/11938#issuecomment-1306103766. My question is when to fix this bug in the stable version?

**Comment by DonJayamanne** [comment]
> the stable version has a bug reported in #11938

it's very confusing when dealing with intellisense issues in this issue as they are completely unrelated.

the issue #11938 had been fixed and it will be available in the next stable release.
we already clear bugs once they have been fixed and ready for shipping.ie we don't leave bugs open until a new version had been shipped. that's the general practice ive observed with other github repos as well.
