### ISSUE TITLE
authentication.getpassword is failing in native

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4316]
Was working with the Azure team to fix the azureml widget and had this problem occur:

```
authentication.getpassword is not a function
```

Might be that VS code removed this function recently and we just haven't tested it.

**Comment by rchiodo** [comment]
Yeah they changed it to 'SecretStorage'
https://github.com/microsoft/vscode/blob/01089c0a5052432594a177f90ad9f3148ec2a6a2/src/vs/vscode.proposed.d.ts#L2346

**Comment by DonJayamanne** [comment]
Validated

**Comment by Bakerbakura** [comment]
Hi, is there any idea when this fix will be released? I'm guessing in the next release of the extension?
Unfortunately because of this issue using notebooks on VSCode is broken for me, since I need to specify a custom server as in #4330.

**Comment by rchiodo** [comment]
Sorry but remote isn't currently supported for insiders. (Which will be fixed in our next release too). Next release should be sometime this month.

**Comment by rchiodo** [comment]
You could use a nightly build however. Like from here:
https://github.com/microsoft/vscode-jupyter/suites/1952593259/artifacts/38669570

**Comment by Bakerbakura** [comment]
> Sorry but remote isn't currently supported for insiders. (Which will be fixed in our next release too). Next release should be sometime this month.

The server I'm connecting to isn't exactly remote: I have a SageMath installation which comes bundled with its own Python and Jupyter, so I run that Jupyter server on my local machine and on the normal VSCode (non-native notebooks) I specify the server as something like `localhost:8888/?token=fgfgsdfgcsdfgscdfsdg`. Does this count as a remote server in your definition?

I'll try installing a nightly build and see if that works.

**Comment by rchiodo** [comment]
Sorry but yes that's a 'remote' server. Any time you specify the URI (instead of having us run the kernel) it's remote. Internally remote means we communicated to a jupyter server that's running somewhere. Non-remote/Local means we start kernels ourselves.

**Comment by Bakerbakura** [comment]
Yes! That nightly build works. Thanks!

**Comment by astrowonk** [comment]
It would be delightful if the nightly builds could be available easily via Extensions installer ala the way the remote extension nightly is in there. Or even like the Python extensions a preference that downloads from a nightly channel.
